version: '3'

services:
  web:
    build: ./web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./web:/web
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: ./app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: npm install
    command: npm uninstall vue-cli
    command: npm run serve
volumes:
  bundle:
  postgres-data:
  node_modules:
